title: "Cristoffer Santos | Ciência de Dados"
author: "Cristoffer Gregori"
description: "Portfólio acadêmico e profissional. Projetos de estatística, análise de dados e documentação."
url: "https://cristoffer-santos.github.io"
baseurl: ""

# Tema padrão limpo do GitHub
theme: minima

# Páginas do menu superior
header_pages:
  - index.md

markdown: kramdown
